### ISSUE TITLE
Implement From<f64> for BigInt

### ISSUE THREAD

**Issue by adolfogonzalez3** [rust-num/num-bigint#117]
It looks like BigInt doesn't have a From<f64> implemented. Is it possible to add this feature or is there some problems preventing this from happening?

**Comment by cuviper** [comment]
`From` is supposed to be an infallible conversion, but there's no `BigInt` value possible for infinity or NaN. Instead we have implemented `FromPrimitive` which returns an `Option`, so failure is possible. Even then, it's not a precise conversion since any fractional part of `f64` will be truncated.

**Comment by adolfogonzalez3** [comment]
Okay that makes sense. Thank you for your response. I will close the issue.
