### ISSUE TITLE
Infinite not being used

### ISSUE THREAD

**Issue by notoria** [rust-num/num-bigint#161]
Example:
```Rust
extern crate num;

use num::{BigInt, BigRational, ToPrimitive};

fn main() {
    let n = BigInt::from(-2);
    let n = n.pow(4001);
    println!("{:?}", n.to_f64());
    let r = BigRational::from(n);
    println!("{:?}", r.to_f64());
}
```
Result:
```
None
Some(-inf)
```
I was expecting some minus infinite and got none. A workaround is to convert to `BigRational` but it is expensive, a clone is required.

**Comment by cuviper** [comment]
You can also see `ToPrimitive` sticking to finite values when narrowing, e.g. `std::f64::MAX.to_f32()` returns `None`. It's been that way ever since it was first created in rust-lang/rust#9250 (specifically [here](https://github.com/rust-lang/rust/blob/cb240197441723fed70e4076d9eba460d8f209ba/src/libstd/num/num.rs#L576-L591)), and it doesn't appear that this point was debated.

At that time, bigints only directly supported converting to 64-bit integers, and floats would convert from there by the trait default, so larger values would just be `None`. Then rust-num/num#145 added explicit conversions from bigints to floats, noting that `None` was used instead of `Some(INFINITY)`, but we didn't debate that point.

So this is actually inconsistent on `BigRational`'s part, which is relatively recent: rust-num/num-rational#52.

That's not to insist that we shouldn't change, but we should be careful and consistent about it.

**Comment by cuviper** [comment]
Another inconsistency: `u128::MAX.to_f32()` returns `Some(INFINITY)`.

**Comment by notoria** [comment]
Understood, thank you for clarifying the situation, closing.

**Comment by cuviper** [comment]
I was starting to think we _should_ change -- do you think not?

**Comment by notoria** [comment]
To make it consistent? Yes. Would it be for finite value or would infinite value be included?

**Comment by cuviper** [comment]
I think we should include infinities -- if nothing else, the fact that they can be positive or negative is better than `None`.

**Comment by notoria** [comment]
Agree. Reopening to track the issue.
