### ISSUE TITLE
How to use with const values

### ISSUE THREAD

**Issue by AurelienFT** [rust-num/num-bigint#232]
I want to use this package to create constant values. For example I want to create a const with 100 into. I have tried both : 
```rust
pub const HUNDRED: BigInt = match BigInt::parse_bytes("100".as_bytes(), 10) {
    Some(x) => x,
    None => BigInt::default()
};
```
and
```rust
pub const HUNDRED: BigInt = BigInt::parse_bytes("100".as_bytes(), 10).unwrap();
```
and
```rust
pub const HUNDRED: BigInt = BigInt::from(1000000000i32);
```
For the easy use of my package I don't want to keep them as Option and want to unwrap them as I'm sure what is the content because it's const. How can I create it from a decimal form to have a constant ?

**Comment by cuviper** [comment]
This is discussed in #181, but we can't do this in general because `Vec` is only constant for its empty `Vec::new()`.

I do suggest that `From` is a better choice when a known value is small enough to fit in a primitive integer, but we still can't create that as a `const`. One possibility is to use `once_cell` to create a static [`Lazy`](https://docs.rs/once_cell/1.9.0/once_cell/sync/struct.Lazy.html) value instead.

**Comment by AurelienFT** [comment]
Ok I close in favor of #181 then.
