### ISSUE TITLE
Newbie question: How to convert primitive integer to `BigInt`?

### ISSUE THREAD

**Issue by Rudxain** [rust-num/num-bigint#242]
I'm new to Rust and even more noob at using this library. I've read all I could from the official library docs and found the trait `to_bigint` but I always get compiler errors no matter what syntax I use. I also found `BigInt::new` and properly provided the `enum` `Sign` argument AND the `vec`tor argument, but Rust-analyzer tells me `BigInt` is a `struct` (even though it properly detects the `new` function from that namespace). `analyzer` also tells me that I can't assign `static`s nor `const`s to return values from that function, yet I get EVEN MORE errors if I use `let` or `let mut`. I tried everything, but can't get my code to work.

This is the code
```rust
const limPos: BigInt = BigInt::new(Sign::Plus, vec![0,1,0,1]);
const limNeg: BigInt = BigInt::new(Sign::Minus, vec![0,0,1,1]);
```
I also tried
```rust
static limPos: BigInt = ((1 << 68) | 1).to_bigint().unwrap();
static limNeg: BigInt = ~((-1 << 32) | 1).to_bigint().unwrap();
```

My `Cargo.toml` dependencies are `num-traits` and `num-bigint`

BTW, does `new` interpret the `u32`-sized "digits" as little-endian or big-endian? I assumed it's BE. I don't mean the byte order, I mean the word order, but knowing the byte order may also be helpful

**Comment by cuviper** [comment]
The easiest way to create `BigInt` from primitive integers is using the `From` trait, which is in the prelude, so it's always in scope. That is an infallible conversion, something like `BigInt::from((1i128 << 68) | 1)`.

However, none of `BigInt`'s constructors are constant, due to the `Vec` allocation for its digits, so you can't directly use this in `const` or `static` values. See #181 and #232 for some prior discussion on that. A static [`Lazy`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html) wrapper is probably the easiest workaround for that.

> BTW, does `new` interpret the `u32`-sized "digits" as little-endian or big-endian? I assumed it's BE.

The docs say "The base 2<sup>32</sup> digits are ordered least significant digit first." -- i.e. little-endian.

**Comment by Rudxain** [comment]
Thank you for the info. And now that I think about it, little-endian makes more sense. If I made a BigInt lib I would also use little-endian order

**Comment by Rudxain** [comment]
I tried this code
```rust
let limPos = BigInt::from((1i128 << 68) | 1);
```

But I get errors from rust-analyzer saying "expected bang, semicolon, item, etc". I tried adding the "!" char and it fixed some errors:
```rust
let limPos = BigInt::from!((1i128 << 68) | 1);
```

**Comment by cuviper** [comment]
Your first version works fine on the Rust playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b286d0690561ff448c8485b139e18006

Can you share a similar playground that shows the errors you're seeing?

**Comment by Rudxain** [comment]
That's very strange, I created a new empty file and pasted the playground code and it worked correctly. I guess I have to share my full code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=612bcde0419aef8dbc17e50bc6e1f1e2

**Comment by cuviper** [comment]
Here's my attempt at fixing your code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=264353b74a5a85451d25ad854fd40edc

* `let` can only be used in a function scope. To define a global you need `static`, and as I mentioned before you can use `Lazy` to get around the problem of needing `const` initialization for that.
  * You'll see I also dereferenced `*limPos` etc. everywhere those are used, which is how you work through `Lazy`. You might also want `&*limPos` to borrow a reference to the inner value, since `BigInt` isn't a `Copy`-able type, but that's implicit in comparisons like `<`.
* Related to copying, I added a `clone()` where you initialize `m`, and also changed a few places to `&n` to avoid moving `n` in temporary expressions.

Here's another version with formatting and style changes applied, and a few other idiomatic tweaks:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1157b74e6fa9cb5009a7345ab1ec332e

**Comment by Rudxain** [comment]
Thank you a lot! For now I'll declare `lim_pos` and `lim_neg` locally within `collatz_check`. When I have the need for `static`s, I'll use `once-cell`
