### ISSUE TITLE
Feature request: trim trailing zeros

### ISSUE THREAD

**Issue by Rudxain** [rust-num/num-bigint#254]
A dedicated fn that {remove/strip/trim}s TZs would be nice. Currently, my userland implementation is:
```rust
fn trim(n: BigInt) -> BigInt {
	match n.trailing_zeros() {
		Some(z) => n >> z,
		None => n
	}
}
```

I have done some benchmarks, and it's faster than this:
```rust
fn trim(mut n: BigInt) -> BigInt {
	if !n.is_zero() {
		while !n.bit(0) {
			n >>= 1;
		}
	};
	n
}
```

But I'm not sure if shifting after calling `trailing_zeros` would shift twice, having worse performance than trimming in a single pass. I guess `rustc` should be smart enough to shift once? Please correct me if I'm wrong

**Comment by cuviper** [comment]
Your `trim` function looks fine to me! That is certainly better than shifting one bit at a time -- O(n) rather than O(n<sup>2</sup>).

I'm not sure it's a good general-purpose method to add here though, because I think most of the time when using this, you would also want to know how many bits were affected. So the separate `trailing_zeros` and shift operation seem right to me.

> But I'm not sure if shifting after calling `trailing_zeros` would shift twice,

`trailing_zeros` does not do any shifting, if that's what you're asking. It searches the internal data for the least-significant non-zero digit, then counts the primitive `trailing_zeros` in that digit plus the bit count of the lower full-zero digits.

> I guess `rustc` should be smart enough to shift once?

Generally, no, most bigint operations are too much for the compiler to optimize away.

**Comment by cuviper** [comment]
> That's why I propose an alternative, `ctz_trim`, which returns a tuple with format `(trailing_zeros, trimmed)`, similarly to `div_rem`.

There's a difference with `div_rem` because that directly saves computation, whereas separate `div` and `rem` would each have to perform a complete division.

Your proposed `ctz_trim` would have no such benefit, and would probably be implemented exactly as you have already written it. But I think this is not a common operation, and since it's easy to do on your own, we don't need a dedicated method for it.

**Comment by Rudxain** [comment]
From a time complexity POV, you're right, it's not worth implementing: `div` is O(n^2) in the worst case, and 2 divs would be O( 2(n^2) ) so it makes sense to avoid dividing as much as possible. OTOH, `ctz` and `trim` are O(n) each, together O(2n), it's not much of a difference.

But what if we used an algorithm like this? (pseudocode):

1. Find least significant non-zero BigDigit, store the result in a variable.
2. Deallocate all zero BDs.
3. Find set LSB and shift all words accordingly, if necessary (if LSW/LSBD is odd)
4. Return tuple containing the shifted BigInt and CTZ * wordsize + indexOf LSB

That algorithm should be faster than CTZ followed by a shift, because both operations are being computed simultaneously in a single pass.

A (naive) userland implementation would require shifting 1 word per iteration, potentially triggering multiple deallocation requests, then doing a binary search on the non-zero word, which is prone to bugs (except when copy-pasting code).

A smarter user implementation would obviously take advantage of the low-level access to the BigDigits provided by the library API, but what if the internal representation changes between versions? (I know this is not a problem, because of SemVer, but it could happen accidentally to someone)

**Comment by cuviper** [comment]
> 2\. Deallocate all zero BDs.

There's nothing to directly deallocate here, as those are primitive `u32` or `u64` (depending on the target). The only allocation is the `Vec<BigDigit>`, which you'll just shift within later.

> A smarter user implementation would obviously take advantage of the low-level access to the BigDigits provided by the library API, but what if the internal representation changes between versions? (I know this is not a problem, because of SemVer, but it could happen accidentally to someone)

The API does not provide direct access to the internal digits, exactly so that we can make changes without breaking semver. That's why providing `trailing_zeros` does make sense for its optimal implementation.

**Comment by Rudxain** [comment]
> those are primitive `u32` or `u64`

Right, they're on the stack, so the correct term would be to "pop the frames"?

> The only allocation is the `Vec<BigDigit>`

Exactly, because it's on the heap (I'm still getting used to the terminology, lol).

> The API does not provide direct access to the internal digits, exactly so that we can make changes without breaking semver. That's why providing `trailing_zeros` does make sense for its optimal implementation.

Oooh, so that's why `BigInt`s can be converted to so many "formats" (Vec<u32>, Vec<i64>, etc...) it's because of the modular architecture. Thank you so much for explaining! (and thank you for your patience)
